import { SQSClient, SendMessageCommand } from "@aws-sdk/client-sqs";

const QUEUE_URL = process.env.AWS_SQS_QUEUE_URL;
const SQS_REGION = process.env.AWS_REGION; 

// ── SQS client (uses dedicated SQS credentials from env) ─────────────────────
const sqsClient = new SQSClient({
  region: SQS_REGION,
  credentials: {
    accessKeyId: process.env.AWS_SQS_ACCESS_KEY_ID,
    secretAccessKey: process.env.AWS_SQS_SECRET_ACCESS_KEY,
  },
});

/**
 * Enqueue a new order request to the SQS FIFO queue.
 *
 * FIFO ordering: MessageGroupId = outletId ensures all orders for the same
 * outlet are processed one-at-a-time in arrival order by the consumer worker.
 *
 * The consumer handles:
 *   - Inventory availability check
 *   - Atomic inventory decrement ($inc with $gte guard)
 *   - Order document creation
 *   - Mock payment
 *   - Socket events (order:new, inventory:update)
 *
 * @param {Object} params
 * @param {Array}  params.items          - [{ id, name, quantity, price }]
 * @param {number} params.totalAmount    - Total order price
 * @param {Object} params.paymentDetails - { name, upiId }
 * @param {string} params.outletId       - Outlet ObjectId string
 * @param {string} params.tenantId       - Tenant ObjectId string
 * @param {string} params.kioskId        - Kiosk ObjectId string (used in dedup ID)
 * @param {string} params.correlationId   - UUID generated by the HTTP handler; links
 *                                          the SQS message back to the waiting kiosk.
 */
export async function sendOrderMessage({ items, totalAmount, correlationId, paymentDetails, outletId, tenantId, kioskId }) {
  if (!QUEUE_URL) {
    throw new Error("AWS_SQS_QUEUE_URL is not set in environment variables");
  }

  if(!outletId || !tenantId || !kioskId || !items || !totalAmount || !paymentDetails || !correlationId) {
    throw new Error("Invalid order parameters");
  }

  const messageBody = JSON.stringify({
    correlationId,
    outletId,
    tenantId,
    kioskId,
    items,
    totalAmount,
    paymentDetails,
  });

  const command = new SendMessageCommand({
    QueueUrl: QUEUE_URL,
    MessageBody: messageBody,
    // ── FIFO attributes ───────────────────────────────────────────────────────
    // Orders for the same outlet are processed sequentially in the consumer.
    MessageGroupId: outletId,
    // Prevents duplicate delivery if the producer retries within the 5-minute window.
    MessageDeduplicationId: correlationId,
  });

  try {
    const result = await sqsClient.send(command);
    console.log(
      `[SQS producer] Order enqueued — correlationId: ${correlationId} | outletId: ${outletId} | MessageId: ${result.MessageId}`
    );
    return result;
  } catch (err) {
    console.error(
      `[SQS producer] Failed to enqueue order for outlet ${outletId}:`,
      err.message
    );
    throw err;
  }
}
